config/routes.rb
Rorup4q::Application.routes.draw do
  resources :bug_build_xrefs

  resources :bug_histories

  resources :fixing_codes
  get "fixing_code/get_subs" => "fixing_codes#get_subs"
  get "fixing_code/select_a_file" => "fixing_codes#select_a_file"
  get "fixing_code/re_select" => "fixing_codes#re_select"
  get "fixing_code/replace_file" => "fixing_codes#replace_file"
  get "fixing_code/to_commit" => "fixing_codes#to_commit"
  get "fixing_code/show_diffs" => "fixing_codes#show_diffs"
  get "fixing_code/show_diff_details" => "fixing_codes#show_diff_details"
  get "fixing_code/commit_files" => "fixing_codes#commit_files"

  resources :bugs
  get "bug/attach_to_bug" => "bugs#attach_to_bug"
  get "bug/get_attach" => "bugs#get_attach"
  get "bug/remove_attach" => "bugs#remove_attach"
  get "bug/filter" => "bugs#filter"
  get "bug/get_sub_items" => "bugs#get_sub_items"
  get "bug/remove_link" => "bugs#remove_link"
  get "bug/no_relate" => "bugs#no_relate"
  get 'bug/link_to_testcase' => 'bugs#link_to_testcase'
  get 'bug/change_feature' => 'bugs#change_feature'
  get 'bug/show_commits' => 'bugs#show_commits'
  get 'bug/hide_commits' => 'bugs#hide_commits'
  get 'bug/fix' => 'bugs#fix'
    
  resources :repositories
  get 'repository/show_detail' => 'repositories#show_detail'
  get 'repository/hide_detail' => 'repositories#hide_detail'
  get 'repository/show_commit' => 'repositories#show_commit'
  get 'repository/diff_commits' => 'repositories#diff_commits'

  root :to => "admin#index"

  resources :user_testcase_xrefs

  resources :testcase_bug_xrefs

  resources :user_bug_xrefs
  
  resources :builds

  resources :user_feature_xrefs

  resources :user_product_xrefs

  get "admin/index"

  resources :testcases
  get "testcase/add_link" => "testcases#add_link"
  get "testcase/remove_link" => "testcases#remove_link"
  get "testcase/update_status" => "testcases#update_status"
  get "testcase/save_status" => "testcases#save_status"
  get "testcase/no_relate" => "testcases#no_relate"
  get "testcase/filter" => "testcases#filter"
  get "testcase/link_to_bug" => 'testcases#link_to_bug'
  get 'testcase/bug_links' => 'testcases#bug_links'

  resources :attachments

  resources :features

  resources :user_component_xrefs

  resources :components

  resources :user_track_xrefs

  resources :tracks
  get "track/delete_repository" => "tracks#delete_repository"

  resources :products
  get "product/add_member" => "products#add_member"
  get "product/filter" => "products#filter"

  resources :users

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'stats' => 'stats#index'
end

app/models/testcase_bug_xref.rb
class TestcaseBugXref < ActiveRecord::Base
  validates :testcase_id, :presence=>true
  validates :bug_id, :presence=>true
  belongs_to :testcase
  belongs_to :bug
end

app/controllers/testcase_bug_xrefs_controller.rb
class TestcaseBugXrefsController < ApplicationController
  # GET /testcase_bug_xrefs
  # GET /testcase_bug_xrefs.xml
  def index
    @testcase_bug_xrefs = TestcaseBugXref.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @testcase_bug_xrefs }
    end
  end

  # GET /testcase_bug_xrefs/1
  # GET /testcase_bug_xrefs/1.xml
  def show
    @testcase_bug_xref = TestcaseBugXref.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @testcase_bug_xref }
    end
  end

  # GET /testcase_bug_xrefs/new
  # GET /testcase_bug_xrefs/new.xml
  def new
    @testcase_bug_xref = TestcaseBugXref.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @testcase_bug_xref }
    end
  end

  # GET /testcase_bug_xrefs/1/edit
  def edit
    @testcase_bug_xref = TestcaseBugXref.find(params[:id])
  end

  # POST /testcase_bug_xrefs
  # POST /testcase_bug_xrefs.xml
  def create
    @testcase_bug_xref = TestcaseBugXref.new(params[:testcase_bug_xref])

    respond_to do |format|
      if @testcase_bug_xref.save
        format.html { redirect_to(@testcase_bug_xref, :notice => 'Testcase bug xref was successfully created.') }
        format.xml  { render :xml => @testcase_bug_xref, :status => :created, :location => @testcase_bug_xref }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @testcase_bug_xref.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /testcase_bug_xrefs/1
  # PUT /testcase_bug_xrefs/1.xml
  def update
    @testcase_bug_xref = TestcaseBugXref.find(params[:id])

    respond_to do |format|
      if @testcase_bug_xref.update_attributes(params[:testcase_bug_xref])
        format.html { redirect_to(@testcase_bug_xref, :notice => 'Testcase bug xref was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @testcase_bug_xref.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /testcase_bug_xrefs/1
  # DELETE /testcase_bug_xrefs/1.xml
  def destroy
    @testcase_bug_xref = TestcaseBugXref.find(params[:id])
    @testcase_bug_xref.destroy

    respond_to do |format|
      format.html { redirect_to(testcase_bug_xrefs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/testcase_bug_xrefs_helper.rb
module TestcaseBugXrefsHelper
end

app/views/testcase_bug_xrefs/_form.html.erb
<%= form_for(@testcase_bug_xref) do |f| %>
  <% if @testcase_bug_xref.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testcase_bug_xref.errors.count, "error") %> prohibited this testcase_bug_xref from being saved:</h2>

      <ul>
      <% @testcase_bug_xref.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :testcase_id %><br />
    <%= f.text_field :testcase_id %>
  </div>
  <div class="field">
    <%= f.label :bug_id %><br />
    <%= f.text_field :bug_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testcase_bug_xrefs/edit.html.erb
<h1>Editing testcase_bug_xref</h1>

<%= render 'form' %>

<%= link_to 'Show', @testcase_bug_xref %> |
<%= link_to 'Back', testcase_bug_xrefs_path %>

app/views/testcase_bug_xrefs/index.html.erb
<h1>Listing testcase_bug_xrefs</h1>

<table>
  <tr>
    <th>Testcase</th>
    <th>Bug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testcase_bug_xrefs.each do |testcase_bug_xref| %>
  <tr>
    <td><%= testcase_bug_xref.testcase_id %></td>
    <td><%= testcase_bug_xref.bug_id %></td>
    <td><%= link_to 'Show', testcase_bug_xref %></td>
    <td><%= link_to 'Edit', edit_testcase_bug_xref_path(testcase_bug_xref) %></td>
    <td><%= link_to 'Destroy', testcase_bug_xref, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Testcase bug xref', new_testcase_bug_xref_path %>

app/views/testcase_bug_xrefs/new.html.erb
<h1>New testcase_bug_xref</h1>

<%= render 'form' %>

<%= link_to 'Back', testcase_bug_xrefs_path %>

app/views/testcase_bug_xrefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Testcase:</b>
  <%= @testcase_bug_xref.testcase_id %>
</p>

<p>
  <b>Bug:</b>
  <%= @testcase_bug_xref.bug_id %>
</p>


<%= link_to 'Edit', edit_testcase_bug_xref_path(@testcase_bug_xref) %> |
<%= link_to 'Back', testcase_bug_xrefs_path %>