config/routes.rb
Rorup4q::Application.routes.draw do
  resources :bug_build_xrefs

  resources :bug_histories

  resources :fixing_codes
  get "fixing_code/get_subs" => "fixing_codes#get_subs"
  get "fixing_code/select_a_file" => "fixing_codes#select_a_file"
  get "fixing_code/re_select" => "fixing_codes#re_select"
  get "fixing_code/replace_file" => "fixing_codes#replace_file"
  get "fixing_code/to_commit" => "fixing_codes#to_commit"
  get "fixing_code/show_diffs" => "fixing_codes#show_diffs"
  get "fixing_code/show_diff_details" => "fixing_codes#show_diff_details"
  get "fixing_code/commit_files" => "fixing_codes#commit_files"

  resources :bugs
  get "bug/attach_to_bug" => "bugs#attach_to_bug"
  get "bug/get_attach" => "bugs#get_attach"
  get "bug/remove_attach" => "bugs#remove_attach"
  get "bug/filter" => "bugs#filter"
  get "bug/get_sub_items" => "bugs#get_sub_items"
  get "bug/remove_link" => "bugs#remove_link"
  get "bug/no_relate" => "bugs#no_relate"
  get 'bug/link_to_testcase' => 'bugs#link_to_testcase'
  get 'bug/change_feature' => 'bugs#change_feature'
  get 'bug/show_commits' => 'bugs#show_commits'
  get 'bug/hide_commits' => 'bugs#hide_commits'
  get 'bug/fix' => 'bugs#fix'
    
  resources :repositories
  get 'repository/show_detail' => 'repositories#show_detail'
  get 'repository/hide_detail' => 'repositories#hide_detail'
  get 'repository/show_commit' => 'repositories#show_commit'
  get 'repository/diff_commits' => 'repositories#diff_commits'

  root :to => "admin#index"

  resources :user_testcase_xrefs

  resources :testcase_bug_xrefs

  resources :user_bug_xrefs
  
  resources :builds

  resources :user_feature_xrefs

  resources :user_product_xrefs

  get "admin/index"

  resources :testcases
  get "testcase/add_link" => "testcases#add_link"
  get "testcase/remove_link" => "testcases#remove_link"
  get "testcase/update_status" => "testcases#update_status"
  get "testcase/save_status" => "testcases#save_status"
  get "testcase/no_relate" => "testcases#no_relate"
  get "testcase/filter" => "testcases#filter"
  get "testcase/link_to_bug" => 'testcases#link_to_bug'
  get 'testcase/bug_links' => 'testcases#bug_links'

  resources :attachments

  resources :features

  resources :user_component_xrefs

  resources :components

  resources :user_track_xrefs

  resources :tracks
  get "track/delete_repository" => "tracks#delete_repository"

  resources :products
  get "product/add_member" => "products#add_member"
  get "product/filter" => "products#filter"

  resources :users

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'stats' => 'stats#index'
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :track
  include Grit

  validate :must_be_git_path
  validates :name, :presence => true, :uniqueness => true

  def is_main
    return self.track.main_repo_id == self.id
  end

  def get_commits
    repo = Repo.new(self.filepath)
    return repo.commits
  end
  def get_s_commits(bug, s)
    commits_arr = Array.new
    repo = Repo.new(self.filepath)
    repo.commits.each do |c|
      if c.message.include? 'bug'+s
        commits_arr << c
      end
    end
    return commits_arr
  end
  def get_commit_by_id id
    repo = Repo.new(self.filepath)
    return repo.commit(id)
  end
  def earlier_commits c
    repo = Repo.new(self.filepath)
    ecs = repo.commits_between(repo.commits.last, c)
    ecs.pop
    return ecs
  end
  def commits_diff c1, c2
    return Repo.new(self.filepath).diff(c1, c2)
  end

  def get_sub_folders path
    if ! path.include? self.filepath
      path = self.filepath +'/'+ path
    end
    if ! path.end_with? '/'
      oath = path + '/'
    end
    subs = Dir.glob(path+'*')
    sub_folders = Array.new
    subs.each do |s|
      if File.directory? s
        sub_folders << s.split('/')[-1]
      end
    end
    return sub_folders
  end
  def get_sub_files path
    if ! path.include? self.filepath
      path = self.filepath +'/'+ path
    end
    if ! path.end_with? '/'
      oath = path + '/'
    end
    subs = Dir.glob(path+'*')
    sub_files = Array.new
    subs.each do |s|
      if File.file? s
        sub_files << s.split('/')[-1]
      end
    end
    return sub_files
  end

  private
    def must_be_git_path
      if ! self.filepath.ends_with? '/'
        self.filepath = self.filepath + '/'
      end
      files = Dir.glob(self.filepath+'.git')
      errors.add(:filepath, "Invalid Repository Path" ) unless files.size > 0
    end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # GET /repositories
  # GET /repositories.xml
  def index
    @repositories = Repository.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @repositories }
    end
  end

  # GET /repositories/1
  # GET /repositories/1.xml
  def show
    @repository = Repository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/new
  # GET /repositories/new.xml
  def new
    @repository = Repository.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.xml
  def create
    @repository = Repository.new(params[:repository])
    if ! @repository.filepath.ends_with? '/'
      @repository.filepath = @repository.filepath+'/'
    end

    respond_to do |format|
      if @repository.save
        is_main = params[:is_main]
        if is_main
          track = @repository.track
          track.main_repo_id = @repository.id
          track.save
        end
        format.html { redirect_to(@repository, :notice => 'Repository was successfully created.') }
        format.xml  { render :xml => @repository, :status => :created, :location => @repository }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.xml
  def update
    @repository = Repository.find(params[:id])
    if params[:is_main]
      is_main = params[:is_main]
      track = @repository.track
      track.main_repo_id = @repository.id
    else
      is_main = false
      track = @repository.track
      track.main_repo_id = nil
    end
    track.save
    if ! @repository.filepath.ends_with? '/'
      @repository.filepath = @repository.filepath+'/'
    end

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html { redirect_to(@repository, :notice => 'Repository was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.xml
  def destroy
    @repository = Repository.find(params[:id])
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to(repositories_url) }
      format.xml  { head :ok }
    end
  end

  def show_detail
    @repository = Repository.find(params[:id])
    @commits = @repository.get_commits
    render :action => 'show'
  end
  def hide_detail
    @repository = Repository.find(params[:id])
    @commits = nil
    render :action => 'show'
  end
  


  def get_sub_folders path
    repo = Repository.find_by_id(params[:repository_id])
    if ! path.include? repo.filepath
      path = repo.filepath +'/'+ path
    end
    if ! path.end_with? '/'
      oath = path + '/'
    end
    subs = Dir.glob(path+'*')
    sub_folders = Array.new
    subs.each do |s|
      if File.directory? s
        sub_folders << s.split('/')[-1]
      end
    end
    return sub_folders
  end
  def get_sub_files path
    if ! path.include? repo.filepath
      path = repo.filepath +'/'+ path
    end
    if ! path.end_with? '/'
      oath = path + '/'
    end
    subs = Dir.glob(path+'*')
    sub_files = Array.new
    subs.each do |s|
      if File.file? s
        sub_files << s.split('/')[-1]
      end
    end
    return sub_files
  end

  def show_commit
    @bug = Bug.find_by_id(params[:bug_id])
    repo = @bug.feature.component.track.main_repo
    @commit = repo.get_commit_by_id(params[:commit])
    @earlier_commits = repo.earlier_commits(@commit)
    render :action => 'show_commit'
  end

  def diff_commits
    @repo = Repository.find_by_id(params[:id])
    if @commit1 && @commit2
      render :action => 'show_diff'
    else
      render :action => "select_commits"
    end
  end

  def diff_commits_for_bug
    repo = Bug.find_by_id(params[:bug_id]).feature.component.track.main_repo
    @bug = Bug.find_by_id(params[:bug_id])
    @commit = repo.get_commit_by_id(params[:c])
    @earlier_commits = repo.earlier_commits(@commit)
    @diff = repo.commits_diff(repo.get_commit_by_id(params[:c]), repo.get_commit_by_id(params[:earlier_commit]))
    render :action => "show_commit"
  end

end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :track_id, :value=>session[:track_id] %>
  <% @repository.track = Track.find_by_id(session[:track_id]) %>
  <div class="field">
    <%= f.label :name %>: <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %>: <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= label_tag 'Main Repository' %>: <%= check_box_tag 'is_main', true, @repository.track.main_repo==@repository %> Yes
  </div>
  <div class="field">
    <%= f.label 'Local or Remote' %>: <% lrArray = ['LOCAL', 'REMOTE'] %>
    <%= f.select(:lr_flag, options_for_select(lrArray, @repository.lr_flag)) %>
  </div>
  <div class="field">
    <%= f.label 'Manager Type' %>: <% mtArray = ['git', 'svn', 'cvs'] %>
    <%= f.select(:mgr_type, options_for_select(mtArray, @repository.mgr_type)) %>
  </div>
  <div class="field">
    <%= f.label :filepath %>: <%= f.text_field :filepath %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/_show_commit.html.erb
<%= form_tag '/repository/diff_commits_for_bug' do %>
  <%= label_tag @commit.id %>
  <table>
    <tr>
      <th>Author</th>
      <th>Authored at</th>
      <th>Committer</th>
      <th>Committed at</th>
      <th>Comments</th>
    </tr>
    <tr>
      <td><%= @commit.author %></td>
      <td><%= @commit.authored_date %></td>
      <td><%= @commit.committer %></td>
      <td><%= @commit.committed_date %></td>
      <td><%= @commit.message %></td>
    </tr>
  </table>

  Earlier Commits:<br />
  <%= select_tag :earlier_commit, options_for_select(@earlier_commits.collect{|ec| [ec.committed_date.to_s+': '+ec.message, ec.id]}) %>
  <%= hidden_field_tag :bug_id, @bug.id %>
  <%= hidden_field_tag :c, @commit.id %>
  <%= submit_tag 'Show Diff' %>
<% end %>

<div id='diff'>
  <% if @diff %>
    <%= @diff %>
=================================
    <% @diff.each do |d| %>
      <%= d %><br />
    <% end %>
  <% end %>
</div>

<%= link_to 'Back', @bug %>

app/views/repositories/_show_commits.html.erb
<% if @commits %>
  <% @commits.each do |c| %>
    <%= link_to c.message, :controller => :repositories, :action=>'show_commit', :bug_id=>@bug.id, :commit=>c %><br />
  <% end %>
<% end %>

app/views/repositories/_show_detail.html.erb
<% if @commits %>
  <table>
    <tr>
      <th>Author</th>
      <th>Authored at</th>
      <th>Committer</th>
      <th>Committed at</th>
      <th>Comments</th>
    </tr>
  <% @commits.each do |c| %>
    <tr>
      <td><%= c.author %></td>
      <td><%= c.authored_date %></td>
      <td><%= c.committer %></td>
      <td><%= c.committed_date %></td>
      <td><%= c.message %></td>
    </tr>
  <% end %>
  </table>
  <%= link_to 'Diff', :class=>'fixing_code', :action=>'show_diff' %>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Listing repositories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Track</th>
    <th>LR Flag</th>
    <th></th>
    <th></th>
  </tr>

<% @repositories.each do |repository| %>
  <tr>
    <td><%= link_to repository.name, repository %></td>
    <td><%= repository.track.name %></td>
    <td><%= repository.lr_flag %></td>
    <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
    <td><%= link_to 'Destroy', repository, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render 'form' %>

<% if(session[:track_id]) %>
  <%= link_to 'Back', Track.find(session[:track_id]) %>
<% else %>
  <%= link_to 'Back', repositories_path %>
<% end %>

app/views/repositories/select_commits.html.erb
<% if @diff %>
<% elsif @commit2 %>
<% elsif @commit1 %>
<% else %>
<% end %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<% session[:repository_id] = @repository.id %>

<%= link_to @repository.track.product.name, @repository.track.product %> > <%= link_to @repository.track.name, @repository.track %>

<p>
  <b>Name:</b>
  <%= @repository.name %>
</p>

<% if @repository.is_main %>
  Main Repository of
<% end %>

<%= link_to @repository.track.name, @repository.track %>

<p>
  <b>LR Flag:</b>
  <%= @repository.lr_flag %>
</p>

<p>
  <b>manager Type:</b>
  <%= @repository.mgr_type %>
</p>

<p>
  <b>Filepath:</b>
  <%= @repository.filepath %>
</p>

<%= link_to 'Edit', edit_repository_path(@repository) %><br />
---------------------------------<br />
<% if @commits %>
  <%= link_to 'Hide Detail', :controller => 'repositories', :action => 'hide_detail', :id=>@repository.id %>
  <table>
    <tr>
      <th>Author</th>
      <th>Authored at</th>
      <th>Committer</th>
      <th>Committed at</th>
      <th>Comments</th>
    </tr>
  <% @commits.each do |c| %>
    <tr>
      <td><%= c.author %></td>
      <td><%= c.authored_date %></td>
      <td><%= c.committer %></td>
      <td><%= c.committed_date %></td>
      <td><%= c.message %></td>
    </tr>
  <% end %>
  </table>
  <%= link_to 'Diff', :controller=>'repositories', :action=>'diff_commits', :id=>@repository.id %>
<% else %>
  <%= link_to 'Show Detail', :controller => 'repositories', :action => 'show_detail', :id=>@repository.id %> 
<%end%>

app/views/repositories/show_commit.html.erb
<%= form_tag '/repository/diff_commits' do %>
  <%= label_tag @commit.id %>
  <table>
    <tr>
      <th>Author</th>
      <th>Authored at</th>
      <th>Committer</th>
      <th>Committed at</th>
      <th>Comments</th>
    </tr>
    <tr>
      <td><%= @commit.author %></td>
      <td><%= @commit.authored_date %></td>
      <td><%= @commit.committer %></td>
      <td><%= @commit.committed_date %></td>
      <td><%= @commit.message %></td>
    </tr>
  </table>

  Earlier Commits:<br />
  <%= select_tag :earlier_commit, options_for_select(@earlier_commits.collect{|ec| [ec.committed_date.to_s+': '+ec.message, ec.id]}) %>
  <%= hidden_field_tag :bug_id, @bug.id %>
  <%= hidden_field_tag :c, @commit.id %>
  <%= submit_tag 'Show Diff' %>
<% end %>

<div id='diff'>
  <% if @diff %>
    <%= @diff %>
=================================
    <% @diff.each do |d| %>
      <%= d %><br />
    <% end %>
  <% end %>
</div>

<%= link_to 'Back', @bug %>