config/routes.rb
Rorup4q::Application.routes.draw do
  resources :bug_build_xrefs

  resources :bug_histories

  resources :fixing_codes
  get "fixing_code/get_subs" => "fixing_codes#get_subs"
  get "fixing_code/select_a_file" => "fixing_codes#select_a_file"
  get "fixing_code/re_select" => "fixing_codes#re_select"
  get "fixing_code/replace_file" => "fixing_codes#replace_file"
  get "fixing_code/to_commit" => "fixing_codes#to_commit"
  get "fixing_code/show_diffs" => "fixing_codes#show_diffs"
  get "fixing_code/show_diff_details" => "fixing_codes#show_diff_details"
  get "fixing_code/commit_files" => "fixing_codes#commit_files"

  resources :bugs
  get "bug/attach_to_bug" => "bugs#attach_to_bug"
  get "bug/get_attach" => "bugs#get_attach"
  get "bug/remove_attach" => "bugs#remove_attach"
  get "bug/filter" => "bugs#filter"
  get "bug/get_sub_items" => "bugs#get_sub_items"
  get "bug/remove_link" => "bugs#remove_link"
  get "bug/no_relate" => "bugs#no_relate"
  get 'bug/link_to_testcase' => 'bugs#link_to_testcase'
  get 'bug/change_feature' => 'bugs#change_feature'
  get 'bug/show_commits' => 'bugs#show_commits'
  get 'bug/hide_commits' => 'bugs#hide_commits'
  get 'bug/fix' => 'bugs#fix'
    
  resources :repositories
  get 'repository/show_detail' => 'repositories#show_detail'
  get 'repository/hide_detail' => 'repositories#hide_detail'
  get 'repository/show_commit' => 'repositories#show_commit'
  get 'repository/diff_commits' => 'repositories#diff_commits'

  root :to => "admin#index"

  resources :user_testcase_xrefs

  resources :testcase_bug_xrefs

  resources :user_bug_xrefs
  
  resources :builds

  resources :user_feature_xrefs

  resources :user_product_xrefs

  get "admin/index"

  resources :testcases
  get "testcase/add_link" => "testcases#add_link"
  get "testcase/remove_link" => "testcases#remove_link"
  get "testcase/update_status" => "testcases#update_status"
  get "testcase/save_status" => "testcases#save_status"
  get "testcase/no_relate" => "testcases#no_relate"
  get "testcase/filter" => "testcases#filter"
  get "testcase/link_to_bug" => 'testcases#link_to_bug'
  get 'testcase/bug_links' => 'testcases#bug_links'

  resources :attachments

  resources :features

  resources :user_component_xrefs

  resources :components

  resources :user_track_xrefs

  resources :tracks
  get "track/delete_repository" => "tracks#delete_repository"

  resources :products
  get "product/add_member" => "products#add_member"
  get "product/filter" => "products#filter"

  resources :users

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'stats' => 'stats#index'
end

app/models/user_component_xref.rb
class UserComponentXref < ActiveRecord::Base
  belongs_to :user
  belongs_to :component
end

app/controllers/user_component_xrefs_controller.rb
class UserComponentXrefsController < ApplicationController
  skip_before_filter :authorize, :only => [:create, :update, :delete]

  # GET /user_component_xrefs
  # GET /user_component_xrefs.xml
  def index
    @user_component_xrefs = UserComponentXref.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_component_xrefs }
    end
  end

  # GET /user_component_xrefs/1
  # GET /user_component_xrefs/1.xml
  def show
    @user_component_xref = UserComponentXref.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_component_xref }
    end
  end

  # GET /user_component_xrefs/new
  # GET /user_component_xrefs/new.xml
  def new
    @user_component_xref = UserComponentXref.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_component_xref }
    end
  end

  # GET /user_component_xrefs/1/edit
  def edit
    @user_component_xref = UserComponentXref.find(params[:id])
  end

  # POST /user_component_xrefs
  # POST /user_component_xrefs.xml
  def create
    @user_component_xref = UserComponentXref.new(params[:user_component_xref])

    respond_to do |format|
      if @user_component_xref.save
        format.html { redirect_to(@user_component_xref, :notice => 'User component xref was successfully created.') }
        format.xml  { render :xml => @user_component_xref, :status => :created, :location => @user_component_xref }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_component_xref.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_component_xrefs/1
  # PUT /user_component_xrefs/1.xml
  def update
    @user_component_xref = UserComponentXref.find(params[:id])

    respond_to do |format|
      if @user_component_xref.update_attributes(params[:user_component_xref])
        format.html { redirect_to(@user_component_xref, :notice => 'User component xref was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_component_xref.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_component_xrefs/1
  # DELETE /user_component_xrefs/1.xml
  def destroy
    @user_component_xref = UserComponentXref.find(params[:id])
    @user_component_xref.destroy

    respond_to do |format|
      format.html { redirect_to(user_component_xrefs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/user_component_xrefs_helper.rb
module UserComponentXrefsHelper
end

app/views/user_component_xrefs/_form.html.erb
<%= form_for(@user_component_xref) do |f| %>
  <% if @user_component_xref.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_component_xref.errors.count, "error") %> prohibited this user_component_xref from being saved:</h2>

      <ul>
      <% @user_component_xref.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :component_id %><br />
    <%= f.text_field :component_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_component_xrefs/edit.html.erb
<h1>Editing user_component_xref</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_component_xref %> |
<%= link_to 'Back', user_component_xrefs_path %>

app/views/user_component_xrefs/index.html.erb
<h1>Listing user_component_xrefs</h1>

<table>
  <tr>
    <th>User</th>
    <th>Component</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_component_xrefs.each do |user_component_xref| %>
  <tr>
    <td><%= user_component_xref.user_id %></td>
    <td><%= user_component_xref.component_id %></td>
    <td><%= link_to 'Show', user_component_xref %></td>
    <td><%= link_to 'Edit', edit_user_component_xref_path(user_component_xref) %></td>
    <td><%= link_to 'Destroy', user_component_xref, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User component xref', new_user_component_xref_path %>

app/views/user_component_xrefs/new.html.erb
<h1>New user_component_xref</h1>

<%= render 'form' %>

<%= link_to 'Back', user_component_xrefs_path %>

app/views/user_component_xrefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_component_xref.user_id %>
</p>

<p>
  <b>Component:</b>
  <%= @user_component_xref.component_id %>
</p>


<%= link_to 'Edit', edit_user_component_xref_path(@user_component_xref) %> |
<%= link_to 'Back', user_component_xrefs_path %>