config/routes.rb
Rorup4q::Application.routes.draw do
  resources :bug_build_xrefs

  resources :bug_histories

  resources :fixing_codes
  get "fixing_code/get_subs" => "fixing_codes#get_subs"
  get "fixing_code/select_a_file" => "fixing_codes#select_a_file"
  get "fixing_code/re_select" => "fixing_codes#re_select"
  get "fixing_code/replace_file" => "fixing_codes#replace_file"
  get "fixing_code/to_commit" => "fixing_codes#to_commit"
  get "fixing_code/show_diffs" => "fixing_codes#show_diffs"
  get "fixing_code/show_diff_details" => "fixing_codes#show_diff_details"
  get "fixing_code/commit_files" => "fixing_codes#commit_files"

  resources :bugs
  get "bug/attach_to_bug" => "bugs#attach_to_bug"
  get "bug/get_attach" => "bugs#get_attach"
  get "bug/remove_attach" => "bugs#remove_attach"
  get "bug/filter" => "bugs#filter"
  get "bug/get_sub_items" => "bugs#get_sub_items"
  get "bug/remove_link" => "bugs#remove_link"
  get "bug/no_relate" => "bugs#no_relate"
  get 'bug/link_to_testcase' => 'bugs#link_to_testcase'
  get 'bug/change_feature' => 'bugs#change_feature'
  get 'bug/show_commits' => 'bugs#show_commits'
  get 'bug/hide_commits' => 'bugs#hide_commits'
  get 'bug/fix' => 'bugs#fix'
    
  resources :repositories
  get 'repository/show_detail' => 'repositories#show_detail'
  get 'repository/hide_detail' => 'repositories#hide_detail'
  get 'repository/show_commit' => 'repositories#show_commit'
  get 'repository/diff_commits' => 'repositories#diff_commits'

  root :to => "admin#index"

  resources :user_testcase_xrefs

  resources :testcase_bug_xrefs

  resources :user_bug_xrefs
  
  resources :builds

  resources :user_feature_xrefs

  resources :user_product_xrefs

  get "admin/index"

  resources :testcases
  get "testcase/add_link" => "testcases#add_link"
  get "testcase/remove_link" => "testcases#remove_link"
  get "testcase/update_status" => "testcases#update_status"
  get "testcase/save_status" => "testcases#save_status"
  get "testcase/no_relate" => "testcases#no_relate"
  get "testcase/filter" => "testcases#filter"
  get "testcase/link_to_bug" => 'testcases#link_to_bug'
  get 'testcase/bug_links' => 'testcases#bug_links'

  resources :attachments

  resources :features

  resources :user_component_xrefs

  resources :components

  resources :user_track_xrefs

  resources :tracks
  get "track/delete_repository" => "tracks#delete_repository"

  resources :products
  get "product/add_member" => "products#add_member"
  get "product/filter" => "products#filter"

  resources :users

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'stats' => 'stats#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :owner, :class_name => "User"
  has_many :tracks
  has_many :users, :through => :user_product_xrefs
  has_many :user_product_xrefs

  validates :name, :uniqueness => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :authorize, :only => [:create, :update, :delete]

  # GET /products
  # GET /products.xml
  def index
    session[:condHash] = {}
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new
#    @product[:owner_id] = session[:user_id]

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        if ! params[:user_ids]
          params[:user_ids] = Array.new
        end
        if ! params[:user_ids].include? params[:product][:owner_id]
          params[:user_ids] << params[:product][:owner_id]
        end
        params[:user_ids].each do |ui|
          xref = UserProductXref.new
          xref.product_id = @product.id
          xref.user_id = ui
          xref.save
        end
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])
    xref = UserProductXref.delete_all("product_id="+@product.id.to_s)
    if ! params[:user_ids]
      params[:user_ids] = Array.new
    end
    if ! params[:user_ids].include? params[:product][:owner_id]
      params[:user_ids] << params[:product][:owner_id]
    end
    params[:user_ids].each do |ui|
      xref = UserProductXref.new
      xref.product_id = @product.id
      xref.user_id = ui
      xref.save
    end

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.tracks.each do |t|
      t.destroy
    end
    UserProductXref.where(:product_id=>params[:id]).each do |xref|
      xref.destroy
    end
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end

  def add_member
    xref = UserProductXref.new(:product_id => params[:id], :user_id => params[:member_id])
    if xref.save
      respond_to do |format|
        format.html { render :action => "edit" }
      end
    end
  end
  
  def filter
    @condHash = {}
    params.keys.each do |k|
      if k != 'action' && k != 'controller'
        @condHash[k] = params[k]
      end
    @products = Product.where(@condHash)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>:
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %>:
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :Owner %>:
    <% if ! @product.owner %>
      <% @product.owner_id = session[:user_id] %>
    <% end %>
    <%= collection_select(:product, :owner_id, User.all, :id, :username, :prompt => true) %>
  </div>

  <div class="field">
    <%= f.label :"Select members" %>:<br />
    <% User.all.each do |u| -%>
      <%= check_box_tag("user_ids[]", u.id, @product.users.include?(u)) %>
      <%= label_tag('', u.username) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/filter.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>Desc</th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= link_to product.name, product %></td>
    <td><%= link_to product.owner.username, product.owner %></td>
    <td><%= product.desc %></td>
    <td><%= link_to 'Delete', product, :confirm => 'Are you sure? All related objects would be deleted.', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>
<%= link_to 'All Products', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>Desc</th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= link_to product.name, product %></td>
    <td><%= link_to product.owner.username, product.owner %></td>
    <td><%= product.desc %></td>
    <td><%= link_to 'Delete', product, :confirm => 'Are you sure? All related objects would be deleted.', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% session[:product_id] = @product.id %>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Owner:</b>
  <%= link_to @product.owner.username, @product.owner %>
</p>

<p>
  <b>Desc:</b>
  <%= @product.desc %>
</p>

<p>
  <b>Tracks:</b><br />
  <% @product.tracks.each do |track| %>
    <%= link_to track.name, track_path(track) %>
    <%= link_to 'Delete', track, :confirm => 'Are you sure? All related objects would be deleted.', :class=>:track, :method => :delete %><br />
    <br />
  <% end %>


  <% session[:product_id] = @product.id %>
  <%= link_to 'New Track', new_track_path %>
</p>

<p>
  <b>Users:</b><br />
  <% @product.users.each do |user| %>
    <%= link_to user.username, user %>
    <br />
  <% end %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %>